# Site settings
title: Zhk Blog
SEOTitle: 可乐君的博客 | Zhk Blog
header-img: img/home-bg.jpg
email: zk@nptever.com
description: "关于前端与设计、爱生活爱拉芳 | 可乐君，Web & Mobile Lover，Front-End Engineer，UX Designer | 这里是 @Zhk可乐君 的个人博客，与你一起发现更大的世界。"
keyword: "可乐君, Zhk可乐君, Zhk, IT民工, Coca Cola JUN, @Zhkpro, 可乐君的博客, Zhk Blog, 博客, 个人网站, 互联网, 前端, 设计, 产品, 依依, Lynn, 依依的男朋友"
url: "http://zhk.ilegant.com/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     1005055670096710
zhihu_username:     zhang-kai-01-25
github_username:    isharer
#twitter_username:  Zhkpro
#facebook_username:  Zhkpro
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# Uyan settings - comment plugin
uyan_username: 2130510

# jiathis settings - Share plugin
jiathis_share: true
jiathis_username: 2130510

# Disqus settings Tip: Net Forbidden
#disqus_username: Zhkblog

# Duoshuo settings Tip: will shutdown 2017-06-1
#duoshuo_username: _your_disqus_short_name_
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: ilegant.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "我思，<br>用双手成就你的梦想"
sidebar-avatar: /img/avatar-sea-zhk.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Su",
        href: "http://su.gallery/"
    },{
        title: "乱序",
        href: "http://mida.re/"
    },{
        title: "前端外刊评论",
        href: "http://qianduan.guru/"
    },{
        title: "天镶的博客",
        href: "http://lingyu.wang/"
    },{
        title: "Luke 的自留地",
        href: "http://hmqk1995.github.io"
    },{
        title: "Ebn's Blog",
        href: "http://ebnbin.com/"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    },{
        title: "解旻的博客",
        href: "http://xieminis.me/"
    },{
        title: "DHong Say",
        href: "http://dhong.co"
    },{
        title: "尹峰以为",
        href: "http://ingf.github.io/"
    },{
        title: "前端神盾局",
        href: "http://wepiaofei.github.io/blog/"
    }
]
